using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyVersionAttribute("0.1.0.8")]
[assembly: AssemblyTitleAttribute("Tosca")]
[assembly: AssemblyProductAttribute("Tosca")]
[assembly: AssemblyDescriptionAttribute("For the exclusive use of Tosca Web Solutions.")]
[assembly: AssemblyTrademarkAttribute("All rights reserved, Tosca Web Solutions")]
[assembly: AssemblyFileVersionAttribute("0.1.0.8")]
[assembly: AssemblyCopyrightAttribute("Tosca Web Solutions, original author or authors")]
[assembly: AssemblyCompanyAttribute("Tosca Web Solutions")]

